### ISSUE TITLE
[cpp] Ignoring return value of function declared with 'nodiscard' attribute

### ISSUE THREAD

**Issue by ntrifunovic** [real-logic/aeron#819]
There is C++ error of ignoring return value of function declared with `nodiscard` attribute in version 1.25.0.

Here is the log of the error compiler reports:
```
In file included from com_github_real_logic_aeron/aeron-archive/src/main/cpp/client/ArchiveProxy.cpp:22:
com_github_real_logic_aeron/aeron_archive_client/AuthConnectRequest.h:887:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
        writer.encodedCredentials();
        ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from external/com_github_real_logic_aeron/aeron-archive/src/main/cpp/client/ArchiveProxy.cpp:48:
com_github_real_logic_aeron/aeron_archive_client/ChallengeResponse.h:624:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
        writer.encodedCredentials();
```

**Comment by mjpt777** [comment]
This looks like you have not regerated the codecs. Aeron 1.25.0 using SBE 1.16.0 which does not generate that code. It looks like you are using an old version of SBE with the latest version of Aeron.

What build process are you using?

**Comment by tmontgomery** [comment]
This looks like you are using C++17 which adds the nodiscard. Try C++11 for compilation of the Aeron C++ API.

**Comment by ntrifunovic** [comment]
I am using Bazel and Clang8. 
I have resolved the issue now. The issue was with the build system and its caching not with Aeron.

Martin thank you for your response!

On a side note that might be of interest to others that: When updating to 1.25.0 I had to define `_POSIX_C_SOURCE=200809L` macro in my build system. 
Without it compilation would fail with:

```
xternal/com_github_real_logic_aeron/aeron-driver/src/main/c/util/aeron_clock.c:27:9: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    if (clock_gettime(CLOCK_MONOTONIC, &ts) < 0)
        ^
external/com_github_real_logic_aeron/aeron-driver/src/main/c/util/aeron_clock.c:27:23: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    if (clock_gettime(CLOCK_MONOTONIC, &ts) < 0)
                      ^
external/com_github_real_logic_aeron/aeron-driver/src/main/c/util/aeron_clock.c:58:9: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    if (clock_gettime(CLOCK_REALTIME, &ts) < 0)
        ^
external/com_github_real_logic_aeron/aeron-driver/src/main/c/util/aeron_clock.c:58:23: error: use of undeclared identifier 'CLOCK_REALTIME'
    if (clock_gettime(CLOCK_REALTIME, &ts) < 0)
```

This was not needed in previous versions of Aeron, seams like it is needed after this change https://github.com/real-logic/aeron/commit/be37595ee22f9325e77e9834475f4a44da7fe5ec.
