### ISSUE TITLE
Build fails on clang 3.9, 4 & 5 (not 6)

### ISSUE THREAD

**Issue by helmesjo** [real-logic/aeron#544]
I've created a [conan package for aeron](https://github.com/helmesjo/conan-aeron). It [fails when building](https://travis-ci.org/helmesjo/conan-aeron/builds/417223976) with clang (except version 6) with the following error:
```
aeron-client/src/main/cpp/util/MemoryMappedFile.h:42:50: error: unknown type name 'off_t'
    static ptr_t createNew(const char* filename, off_t offset, size_t length)
```

PR #315 changed usages of `size_t` to `off_t`. Was this really necessary to make it compile for windows?

Any suggestions for a workaround?

**Comment by tmontgomery** [comment]
Awesome that you've got a conan package for Aeron! Thanks!

Changing to `off_t` was done more for cleaning up. Don't think it is used for win32 build. `off_t` is a normal type, though, to have for Linux (and most POSIX) anyway. So, that is quite odd that it isn't finding the type. Could this be an include issue (or some sort of compat flag issue?)

**Comment by mjpt777** [comment]
@tmontgomery how do you feel about moving to a convention that each file can compile on its own with dependencies? If a header has dependencies it includes them. This should address such issues.

**Comment by tmontgomery** [comment]
We have this somewhat in the C driver. But, yes, some includes should be moved to the headers in the C++ API.
